### ISSUE TITLE
change download button to "open file location" button

### ISSUE THREAD

**Issue by asafMasa** [MapColonies/image-exporter-client#69]

**Comment by alebinson** [comment]
@asafMasa 
According to this https://stackoverflow.com/questions/28724751/open-local-filesfile-using-chrome
Chrome behaves in secured way and doesn't allow to "open local resources"

In order to enable it following extension might be used
https://chrome.google.com/webstore/detail/enable-local-file-links/nikfmfgobenbhmocjaaboihbeocackld/

Bottom line from Chrome point of view it's not secured.
We should check if this option is available by twicking chrome or not.
